import dash
from dash import html, dcc
import dash_bootstrap_components as dbc
from taskcard import TaskCard, create_task_card_list, load_data_from_json_and_format, generate_task_data_from_runs

# Document Extraction Page Layout
def doc_extraction_layout():
    return html.Div([
        html.Div([
            html.H2("Document Extraction", className="module-title"),
            
            # Tabbed Pages
            dcc.Tabs(
                id="doc-extraction-tabs",
                value="original-tab",
                className="custom-tabs",
                children=[
                    dcc.Tab(
                        label="Original",
                        value="original-tab",
                        className="custom-tab",
                        selected_className="custom-tab--selected",
                        children=[
                            html.Div([
                                html.Div([
                                    # === TASK NAME CONFIGURATION ===
                                    html.Div([
                                        html.H3("Task Name", className="section-title"),
                                        html.Div([
                                            html.Label("Task Name", className="form-label"),
                                            dcc.Input(
                                                id="task-name-original",
                                                placeholder="Enter a name for this task",
                                                value="",
                                                className="form-input"
                                            ),
                                            html.Small("Provide a descriptive name for this document extraction task", className="form-hint")
                                        ], className="form-group")
                                    ], className="section-container"),
                                    
                                    # === DATA AND SAVE CONFIGURATION ===
                                    html.Div([
                                        html.H3("Data and Save Configuration", className="section-title"),
                                        # Configuration load status display (changed to modal trigger)
                                        html.Div([
                                            html.Button(
                                                "Display Current Config Status",
                                                id="original-config-status-btn",
                                                className="btn btn-outline-info",
                                                style={"marginBottom": "10px", "display": "none"}
                                            ),
                                            html.Div(id="original-config-load-status", style={"display": "none"}),
                                        ]),
                                        html.Div([
                                            html.Label("Dataset Path", className="form-label"),
                                            dcc.Input(
                                                id="dataset-path",
                                                placeholder="path/to/your/dataset.json",
                                                className="form-input"
                                            ),
                                            html.Small([
                                                "Path to the dataset file that contains documents to be extracted (JSON, CSV, TSV, or Excel format). It is recommended to use the ",
                                                html.Code("_dataset.json", style={"backgroundColor": "#f3f4f6", "padding": "2px 4px", "borderRadius": "3px"}),
                                                " file generated by the Document Parsing function.",
                                                html.Br(),
                                                html.Br(),
                                                "If you haven't parsed your documents yet, use the Document Parsing function first to generate the ",
                                                html.Code("_dataset.json", style={"backgroundColor": "#f3f4f6", "padding": "2px 4px", "borderRadius": "3px"}),
                                                " file. This file will contain structured data from your documents that can be used for extraction."
                                            ], className="form-hint", style={"lineHeight": "1.5", "border": "1px solid #e1e5e9", "borderLeft": "4px solid #3b82f6", "borderRadius": "8px", "padding": "16px", "backgroundColor": "#f8f9fa"})
                                        ], className="form-group"),
                                        html.Div([
                                            html.Label("Save Directory", className="form-label"),
                                            dcc.Input(
                                                id="save-dir",
                                                placeholder="path/to/save/results",
                                                className="form-input"
                                            ),
                                            html.Small([
                                                "Directory path where extraction results will be saved. The results will be stored in a ",
                                                html.Code("result.json", style={"backgroundColor": "#f3f4f6", "padding": "2px 4px", "borderRadius": "3px"}),
                                                " file in the specified directory.",
                                                html.Br(),
                                                html.Br(),
                                                "Make sure the directory exists and you have write permissions. The result file will contain all extracted data in JSON format."
                                            ], className="form-hint", style={"lineHeight": "1.5", "border": "1px solid #e1e5e9", "borderLeft": "4px solid #3b82f6", "borderRadius": "8px", "padding": "16px", "backgroundColor": "#f8f9fa"})
                                        ], className="form-group")
                                    ], className="section-container"),

                                    # === INPUT FIELDS ===
                                    html.Div([
                                        html.H3("Input Fields", className="section-title"),
                                        html.Small([
                                            "Input fields are the fields from your ",
                                            html.Code("_dataset.json", style={"backgroundColor": "#f3f4f6", "padding": "2px 4px", "borderRadius": "3px"}),
                                            " file, such as Result, Method, etc. These fields will be used as input for the extraction process."
                                        ], className="form-hint", style={"lineHeight": "1.5", "border": "1px solid #e1e5e9", "borderLeft": "4px solid #3b82f6", "borderRadius": "8px", "padding": "16px", "backgroundColor": "#f8f9fa", "marginBottom": "15px"}),
                                        html.Button(
                                            "Add InputField",
                                            id="add-input-field",
                                            className="btn",
                                            style={"marginBottom": "15px", "height": "32px", "padding": "0 12px", "fontSize": "12px"}
                                        ),
                                        html.Div(id="input-fields-container", children=[
                                            html.Div([
                                                html.Div(style={"display": "flex", "justifyContent": "space-between", "alignItems": "flex-start"}, children=[
                                                    html.H4("Input Field", style={"margin": "0", "fontSize": "16px"}),
                                                    html.Button(
                                                        "×",
                                                        id={'type': 'delete-input-field', 'index': 'input-field-initial'},
                                                        className="delete-button",
                                                        style={
                                                            "background": "none",
                                                            "border": "none",
                                                            "color": "#6b7280",
                                                            "fontSize": "20px",
                                                            "cursor": "pointer",
                                                            "padding": "0 5px",
                                                            "lineHeight": "1",
                                                            "borderRadius": "4px",
                                                            "hover": {"background": "#f3f4f6", "color": "#ef4444"}
                                                        }
                                                    )
                                                ]),
                                                html.Div(style={"display": "flex", "gap": "20px"}, children=[
                                                    html.Div(style={"flex": 1}, children=[
                                                        html.Label("Input Field Name", className="form-label"),
                                                        dcc.Input(
                                                            id={"type": "input-name", "index": "input-field-initial"},
                                                            placeholder="Method",
                                                            # value="Method",
                                                            className="form-input",
                                                            style={"height": "38px"}
                                                        )
                                                    ]),
                                                    html.Div(style={"flex": 1}, children=[
                                                        html.Label("Input Field Type", className="form-label"),
                                                        dcc.Dropdown(
                                                            id={"type": "input-type", "index": "input-field-initial"},
                                                            options=[
                                                                {"label": "String", "value": "str"},
                                                                {"label": "Integer", "value": "int"},
                                                                {"label": "Float", "value": "float"},
                                                                {"label": "Boolean", "value": "bool"},
                                                                {"label": "List", "value": "list"},
                                                                {"label": "Literal", "value": "literal"},
                                                                {"label": "List Literal", "value": "list_literal"}
                                                            ],
                                                            value="str",
                                                            clearable=False,
                                                            style={"height": "38px","border":"1px solid #e1e5e9","border-radius":"6px"}
                                                        )
                                                    ])
                                                ]),
                                                html.Div([
                                                    html.Label("Input Field Description", className="form-label"),
                                                    dcc.Input(
                                                        id={"type": "input-description", "index": "input-field-initial"},
                                                        placeholder="The method section of a Nature Communications journal article",
                                                        # value="The method section of a Nature Communications journal article",
                                                        className="form-input"
                                                    )
                                                ], className="form-group"),
                                                html.Div(style={"display": "flex", "gap": "20px"}, children=[
                                                    html.Div(style={"flex": 1}, children=[
                                                        dcc.Checklist(
                                                            id="input-add-range",
                                                            options=[{"label": "Add Range Limits", "value": "true"}],
                                                            className="form-checkbox"
                                                        )
                                                    ]),
                                                    html.Div(style={"flex": 1}, children=[
                                                        dcc.Checklist(
                                                            id="input-add-literal",
                                                            options=[{"label": "Add Literal List", "value": "true"}],
                                                            className="form-checkbox"
                                                        )
                                                    ])
                                                ]),
                                                html.Div(id="input-range-container", style={"display": "none"}, children=[
                                                    html.Div([
                                                        html.Label("Range Minimum", className="form-label"),
                                                        dcc.Input(
                                                            id="input-range-min",
                                                            type="number",
                                                            placeholder="Min value",
                                                            className="form-input"
                                                        )
                                                    ], className="form-group"),
                                                    html.Div([
                                                        html.Label("Range Maximum", className="form-label"),
                                                        dcc.Input(
                                                            id="input-range-max",
                                                            type="number",
                                                            placeholder="Max value",
                                                            className="form-input"
                                                        )
                                                    ], className="form-group")
                                                ]),
                                                html.Div(id="input-literal-container", style={"display": "none"}, children=[
                                                    html.Div([
                                                        html.Label("Literal List (comma separated)", className="form-label"),
                                                        dcc.Input(
                                                            id="input-literal-list",
                                                            placeholder="option1,option2,option3",
                                                            className="form-input"
                                                        )
                                                    ], className="form-group")
                                                ])
                                            ], id="input-field-initial", className="section-container", style={"border": "1px solid #e1e5e9", "border-radius": "8px", "padding": "16px", "margin-bottom": "20px"})
                                        ])
                                    ]),

                                    # === OUTPUT FIELDS ===
                                    html.Div([
                                        html.H3("Output Fields", className="section-title"),
                                        html.Small([
                                            "Output fields are the properties contained in the extracted entities. These fields will be used to define what information you want to extract from the input data."
                                        ], className="form-hint", style={"lineHeight": "1.5", "border": "1px solid #e1e5e9", "borderLeft": "4px solid #3b82f6", "borderRadius": "8px", "padding": "16px", "backgroundColor": "#f8f9fa", "marginBottom": "15px"}),
                                        html.Button(
                                            "Add OutputField",
                                            id="add-output-field",
                                            className="btn",
                                            style={"marginBottom": "15px", "height": "32px", "padding": "0 12px", "fontSize": "12px"}
                                        ),
                                        html.Div(id="output-fields-container", children=[
                                            #Initial Output Field
                                            html.Div([
                                                html.Div(style={"display": "flex", "justifyContent": "space-between", "alignItems": "flex-start"}, children=[
                                                    html.H4("Output Field", style={"margin": "0", "fontSize": "16px"}),
                                                    html.Button(
                                                        "×",
                                                        id={'type': 'delete-output-field', 'index': 'output-field-initial'},
                                                        className="delete-button",
                                                        style={
                                                            "background": "none",
                                                            "border": "none",
                                                            "color": "#6b7280",
                                                            "fontSize": "20px",
                                                            "cursor": "pointer",
                                                            "padding": "0 5px",
                                                            "lineHeight": "1",
                                                            "borderRadius": "4px",
                                                            "hover": {"background": "#f3f4f6", "color": "#ef4444"}
                                                        }
                                                    )
                                                ]),
                                                html.Div(style={"display": "flex", "gap": "20px"}, children=[
                                                    html.Div(style={"flex": 1}, children=[
                                                        html.Label("Output Field Name", className="form-label"),
                                                        dcc.Input(
                                                            id={"type": "output-name", "index": "output-field-initial"},
                                                            placeholder="output_field",
                                                            #value="extracted_data",
                                                            className="form-input",
                                                            style={"height": "38px"}
                                                        )
                                                    ]),
                                                    html.Div(style={"flex": 1}, children=[
                                                        html.Label("Output Field Type", className="form-label"),
                                                        dcc.Dropdown(
                                                            id={"type": "output-type", "index": "output-field-initial"},
                                                            options=[
                                                                {"label": "String", "value": "str"},
                                                                {"label": "Integer", "value": "int"},
                                                                {"label": "Float", "value": "float"},
                                                                {"label": "Boolean", "value": "bool"},
                                                                {"label": "List", "value": "list"},
                                                                {"label": "Literal", "value": "literal"},
                                                                {"label": "List Literal", "value": "list_literal"}
                                                            ],
                                                            value="str",
                                                            clearable=False,
                                                            style={"height": "38px","border":"1px solid #e1e5e9","border-radius":"6px"}
                                                        )
                                                    ])
                                                ]),
                                                html.Div([
                                                    html.Label("Output Field Description", className="form-label"),
                                                    dcc.Input(
                                                        id={"type": "output-description", "index": "output-field-initial"},
                                                        placeholder="Description of what to extract",
                                                        #value="Extracted data from documents",
                                                        className="form-input"
                                                    )
                                                ], className="form-group"),
                                                html.Div(style={"display": "flex", "gap": "20px"}, children=[
                                                    html.Div(style={"flex": 1}, children=[
                                                        dcc.Checklist(
                                                            id="output-add-range",
                                                            options=[{"label": "Add Range Limits", "value": "true"}],
                                                            className="form-checkbox"
                                                        )
                                                    ]),
                                                    html.Div(style={"flex": 1}, children=[
                                                        dcc.Checklist(
                                                            id="output-add-literal",
                                                            options=[{"label": "Add Literal List", "value": "true"}],
                                                            className="form-checkbox"
                                                        )
                                                    ])
                                                ]),
                                                html.Div(id="output-range-container", style={"display": "none"}, children=[
                                                    html.Div([
                                                        html.Label("Range Minimum", className="form-label"),
                                                        dcc.Input(
                                                            id="output-range-min",
                                                            type="number",
                                                            placeholder="Min value",
                                                            className="form-input"
                                                        )
                                                    ], className="form-group"),
                                                    html.Div([
                                                        html.Label("Range Maximum", className="form-label"),
                                                        dcc.Input(
                                                            id="output-range-max",
                                                            type="number",
                                                            placeholder="Max value",
                                                            className="form-input"
                                                        )
                                                    ], className="form-group")
                                                ]),
                                                html.Div(id="output-literal-container", style={"display": "none"}, children=[
                                                    html.Div([
                                                        html.Label("Literal List (comma separated)", className="form-label"),
                                                        dcc.Input(
                                                            id="output-literal-list",
                                                            placeholder="option1,option2,option3",
                                                            className="form-input"
                                                        )
                                                    ], className="form-group")
                                                ])
                                            ], id="output-field-initial", className="section-container", style={"border": "1px solid #e1e5e9", "border-radius": "8px", "padding": "16px", "margin-bottom": "20px"})
                                        ])
                                    ]),

                                    # === PROMPT CONFIGURATION ===
                                    html.Div([
                                        html.H3("Prompt Configuration", className="section-title"),
                                        html.Div([
                                            html.Label("Initial Prompt", className="form-label"),
                                            dcc.Textarea(
                                                id="initial-prompt",
                                                placeholder="You are a data analyst organizing the data usage in literature published in the journal Nature Communications. Your goals are: 1. Extract the identifiers of all public datasets mentioned in the literature 2. Extract the identifiers of all non-public datasets (i.e., self-created datasets) provided in the literature 3. Extract the names of all databases used in the literature. Please carefully read the methods section of the literature to completely and accurately extract the above information.",
                                                className="form-textarea",
                                                style={"height": "120px"}
                                            )
                                        ], className="form-group")
                                    ], className="section-container"),

                                    # === PROCESSING SETTINGS ===
                                    html.Div([
                                        html.H3("Processing Settings", className="section-title"),
                                        html.Div([
                                            html.Label("Task", className="form-label"),
                                            dcc.Dropdown(
                                                id="task",
                                                options=[
                                                    {"label": "QA", "value": "QA"},
                                                    {"label": "Extraction", "value": "Extraction"}
                                                ],
                                                value="Extraction",
                                                clearable=False,
                                                style={"height": "38px","border":"1px solid #e1e5e9","border-radius":"6px"}
                                            )
                                        ], className="form-group"),
                                        html.Div([
                                            html.Label("Judging Mode", className="form-label"),
                                            dcc.Dropdown(
                                                id="judging",
                                                options=[
                                                    {"label": "None", "value": ""},
                                                    {"label": "Confidence", "value": "confidence"},
                                                    {"label": "Score", "value": "score"}
                                                ],
                                                value="",
                                                clearable=False,
                                                style={"height": "38px","border":"1px solid #e1e5e9","border-radius":"6px"}
                                            )
                                        ], className="form-group"),
                                        html.Div([
                                            html.Label("Threads", className="form-label"),
                                            dcc.Input(
                                                id="threads",
                                                type="number",
                                                placeholder="6",
                                                value=6,
                                                className="form-input"
                                            )
                                        ], className="form-group"),
                                        html.Div([
                                            html.Label("Multiple Entities", className="form-label"),
                                            dcc.Checklist(
                                            id="multiple",
                                            options=[{"label": "Set true for extracting multiple entities from the document", "value": "true"}],
                                            value=["true"],
                                            className="form-checkbox"
                                        )
                                        ], className="form-group")
                                    ], className="section-container"),

                                    # === ACTION BUTTONS ===
                                    html.Div([
                                        html.Button(
                                            "Start Extraction",
                                            id="start-extraction",
                                            className="btn btn-primary",
                                            style={"height": "38px", "padding": "0 20px"}
                                        ),
                                        # Container for displaying extraction results
                                        html.Div(id="original-extraction-results", style={"marginTop": "20px"})
                                    ], className="form-actions"),

                                ], className="module-container"),
                                
                                # === RECENT NOVEL TASKS (Standalone Section) ===
                                html.Div([
                                    html.H3("Recent Original Tasks", className="section-title"),
                                    html.Div([
                                        html.P("The following are the most recent original extraction tasks, showing task name, creation time, and status information.", 
                                              className="help-text-description", style={"marginBottom": "15px"})
                                    ]),
                                    create_task_card_list(generate_task_data_from_runs("runs/doc_extraction/original", 10, "original-extraction"))
                                ], className="module-container", style={"marginTop": "30px"})
                            ])
                        ]
                    ),
                    
                    dcc.Tab(
                        label="Optimized",
                        value="optimized-tab",
                        className="custom-tab",
                        selected_className="custom-tab--selected",
                        children=[
                            # Optimized tab content
                            html.Div([
                                html.Div([
                                    # === TASK NAME CONFIGURATION ===
                                    html.Div([
                                        html.H3("Task Name", className="section-title"),
                                        html.Div([
                                            html.Label("Task Name", className="form-label"),
                                            dcc.Input(
                                                id="task-name-optimized",
                                                placeholder="Enter a name for this task",
                                                value="",
                                                className="form-input"
                                            ),
                                            html.Small("Provide a descriptive name for this optimized extraction task", className="form-hint")
                                        ], className="form-group")
                                    ], className="section-container"),
                                    
                                    # === REQUIRED PATHS ===
                                    html.Div([
                                        html.H3("Required Paths", className="section-title"),
                                        # 配置加载状态显示（改为弹窗触发器）
                                        html.Div([
                                            html.Button(
                                                "Display Current Config Status",
                                                id="optim-extraction-config-status-btn",
                                                className="btn btn-outline-info",
                                                style={"marginBottom": "10px", "display": "none"}
                                            ),
                                            html.Div(id="optim-extraction-config-load-status", style={"display": "none"}),
                                        ]),
                                        html.Div([
                                            html.Label("Load Directory", className="form-label"),
                                            dcc.Input(
                                                id="optim-load-dir",
                                                placeholder="path/to/optimization/results",
                                                value="",
                                                className="form-input"
                                            ),
                                            html.Small([
                                                "Directory path containing optimized prompts from the Prompt Optimization function. This should be the ",
                                                html.Code("Save Directory", style={"backgroundColor": "#f3f4f6", "padding": "2px 4px", "borderRadius": "3px"}),
                                                " path you specified when running Prompt Optimization.",
                                                html.Br(),
                                                html.Br(),
                                                "If you haven't run Prompt Optimization yet, use the Prompt Optimization function first to generate optimized prompts for your extraction task."
                                            ], className="form-hint", style={"lineHeight": "1.5", "border": "1px solid #e1e5e9", "borderLeft": "4px solid #3b82f6", "borderRadius": "8px", "padding": "16px", "backgroundColor": "#f8f9fa"})
                                        ], className="form-group"),
                                        html.Div([
                                            html.Label("Dataset Path", className="form-label"),
                                            dcc.Input(
                                                id="optim-dataset-path",
                                                value="",
                                                placeholder="path/to/your/dataset.json",
                                                className="form-input"
                                            ),
                                            html.Small([
                                                "Path to the dataset file that contains documents to be extracted (JSON, CSV, TSV, or Excel format). It is recommended to use the ",
                                                html.Code("_dataset.json", style={"backgroundColor": "#f3f4f6", "padding": "2px 4px", "borderRadius": "3px"}),
                                                " file generated by the Document Parsing function.",
                                                html.Br(),
                                                html.Br(),
                                                "If you haven't parsed your documents yet, use the Document Parsing function first to generate the ",
                                                html.Code("_dataset.json", style={"backgroundColor": "#f3f4f6", "padding": "2px 4px", "borderRadius": "3px"}),
                                                " file. This file will contain structured data from your documents that can be used for extraction."
                                            ], className="form-hint", style={"lineHeight": "1.5", "border": "1px solid #e1e5e9", "borderLeft": "4px solid #3b82f6", "borderRadius": "8px", "padding": "16px", "backgroundColor": "#f8f9fa"})
                                        ], className="form-group"),
                                        html.Div([
                                            html.Label("Save Directory", className="form-label"),
                                            dcc.Input(
                                                id="optim-save-dir",
                                                value="",
                                                placeholder="path/to/save/results",
                                                className="form-input"
                                            ),
                                            html.Small([
                                                "Directory path where extraction results will be saved. The results will be stored in a ",
                                                html.Code("result.json", style={"backgroundColor": "#f3f4f6", "padding": "2px 4px", "borderRadius": "3px"}),
                                                " file in the specified directory.",
                                                html.Br(),
                                                html.Br(),
                                                "Make sure the directory exists and you have write permissions. The result file will contain all extracted data in JSON format."
                                            ], className="form-hint", style={"lineHeight": "1.5", "border": "1px solid #e1e5e9", "borderLeft": "4px solid #3b82f6", "borderRadius": "8px", "padding": "16px", "backgroundColor": "#f8f9fa"})
                                        ], className="form-group")
                                    ], className="section-container"),

                                    # === EVALUATION SETTINGS ===
                                    html.Div([
                                        html.H3("Evaluation Settings", className="section-title"),
                                        html.Div([
                                            html.Label("Judging Mode", className="form-label"),
                                            dcc.Dropdown(
                                                id="optim-judging",
                                                options=[
                                                    {"label": "None", "value": ""},
                                                    {"label": "Confidence", "value": "confidence"},
                                                    {"label": "Score", "value": "score"}
                                                ],
                                                value="",
                                                clearable=False,
                                                style={"height": "38px","border":"1px solid #e1e5e9","border-radius":"6px"}
                                            )
                                        ], className="form-group")
                                    ], className="section-container"),

                                    # === PROCESSING SETTINGS ===
                                    html.Div([
                                        html.H3("Processing Settings", className="section-title"),
                                        html.Div([
                                            html.Label("Threads", className="form-label"),
                                            dcc.Input(
                                                id="optim-threads",
                                                type="number",
                                                placeholder="6",
                                                value=6,
                                                className="form-input"
                                            )
                                        ], className="form-group")
                                    ], className="section-container"),

                                    # === ACTION BUTTONS ===
                                    html.Div([
                                        html.Button(
                                            "Start Optimized Extraction",
                                            id="optim-start-extraction",
                                            className="btn btn-primary",
                                            style={"height": "38px", "padding": "0 20px"}
                                        ),
                                        # Container for displaying optimized extraction results
                                        html.Div(id="optim-extraction-results", style={"marginTop": "20px"})
                                    ], className="form-actions"),

                                ], className="module-container"),
                                
                                # === RECENT OPTIMIZED TASKS (Standalone Section) ===
                                html.Div([
                                    html.H3("Recent Optimized Tasks", className="section-title"),
                                    html.Div([
                                        html.P("The following are the most recent optimized extraction tasks, showing task name, creation time, and status information.", 
                                              className="help-text-description", style={"marginBottom": "15px"})
                                    ]),
                                    create_task_card_list(generate_task_data_from_runs("runs/doc_extraction/optm", 10, "optimized-extraction"))
                                ], className="module-container", style={"marginTop": "30px"})
                            ])
                        ]
                    )
                ]
            ),
        ]),
        
        # Configure loading status pop-up
        dbc.Modal(
            [
                dbc.ModalHeader("Configuration Load Status"),
                dbc.ModalBody(id="original-config-modal-body"),
                dbc.ModalFooter(
                    dbc.Button("Close", id="close-original-config-modal", className="ml-auto")
                ),
            ],
            id="original-config-modal",
            is_open=False,
            size="lg"
        ),
        
        # Optimized extraction configuration loading status pop-up
        dbc.Modal(
            [
                dbc.ModalHeader("Optimized Extraction Configuration Status"),
                dbc.ModalBody(id="optim-extraction-config-modal-body"),
                dbc.ModalFooter(
                    dbc.Button("Close", id="close-optim-extraction-config-modal", className="ml-auto")
                ),
            ],
            id="optim-extraction-config-modal",
            is_open=False,
            size="lg"
        )
    ])