from dash import html, dcc
import plotly.graph_objects as go
import dash_bootstrap_components as dbc
from taskcard import TaskCard, create_task_card_list, load_data_from_json_and_format, generate_task_data_from_runs

# Page content function
def prompt_optimization_layout():
    
    return html.Div([
        html.Div([
            html.H2("Prompt Optimization", className="module-title"),
            html.Div([
                # === TASK NAME CONFIGURATION ===
                                    html.Div([
                                        html.H3("Task Name", className="section-title"),
                                        html.Div([
                                            html.Label("Task Name", className="form-label"),
                                            dcc.Input(
                                                id="task-name-prompt-optimization",
                                                placeholder="Enter a name for this task",
                                                value="",
                                                className="form-input"
                                            ),
                        html.Small("Provide a descriptive name for this prompt optimization task", className="form-hint")
                    ], className="form-group"),
                                    ], className="section-container"),
                # === DATA AND SAVE CONFIGURATION ===
                html.Div([
                    html.H3("Data and Save Configuration", className="section-title"),
                    html.Div([
                        html.Label("Dataset Path", className="form-label"),
                        dcc.Input(
                            id="dataset-path",
                            placeholder="path/to/your/dataset.json",
                            className="form-input"
                        ),
                        html.Small([
                            "Path to the dataset file that contains documents to be extracted (JSON, CSV, TSV, or Excel format). It is recommended to use the ",
                            html.Code("_optim_dataset.json", style={"backgroundColor": "#f3f4f6", "padding": "2px 4px", "borderRadius": "3px"}),
                            " file generated by the Build Optimization Dataset function.",
                            html.Br(),
                            html.Br(),
                            "If you haven't build your dataset for optimization yet, use the Build Optimization Dataset function first to generate the ",
                            html.Code("_optim_dataset.json", style={"backgroundColor": "#f3f4f6", "padding": "2px 4px", "borderRadius": "3px"}),
                            " file. This file will contain structured data from your documents that can be used for prompt optimization."
                        ], className="form-hint", style={"lineHeight": "1.5", "border": "1px solid #e1e5e9", "borderLeft": "4px solid #3b82f6", "borderRadius": "8px", "padding": "16px", "backgroundColor": "#f8f9fa"})
                    ], className="form-group"),
                    html.Div([
                        html.Label("Save Directory", className="form-label"),
                        dcc.Input(
                            id="save-dir",
                            placeholder="path/to/save/results",
                            className="form-input"
                        ),
                        html.Small([
                            "Directory path where configuration and optimized prompts will be saved. The results will be stored in this directory.",
                            html.Br(),
                            html.Br(),
                            "It is recommended to create a new directory for each optimization task to keep your results organized.",
                        ], className="form-hint", style={"lineHeight": "1.5", "border": "1px solid #e1e5e9", "borderLeft": "4px solid #3b82f6", "borderRadius": "8px", "padding": "16px", "backgroundColor": "#f8f9fa"})
                    ], className="form-group")
                ], className="section-container"),
                

                
                # === INPUT FIELDS ===
                html.Div([
                    html.H3("Input Fields", className="section-title"),
                    html.Button(
                        "Add InputField",
                        id="add-input-field",
                        className="btn",
                        style={"marginBottom": "15px", "height": "32px", "padding": "0 12px", "fontSize": "12px"}
                    ),
                    html.Div(id="input-fields-container", children=[
                        html.Div([
                            html.Div(style={"display": "flex", "justifyContent": "space-between", "alignItems": "flex-start"}, children=[
                                html.H4("Input Field", style={"margin": "0", "fontSize": "16px"}),
                                html.Button(
                                    "×",
                                    id={'type': 'delete-input-field', 'index': 'input-field-initial'},
                                    className="delete-button",
                                    style={
                                        "background": "none",
                                        "border": "none",
                                        "color": "#6b7280",
                                        "fontSize": "20px",
                                        "cursor": "pointer",
                                        "padding": "0 5px",
                                        "lineHeight": "1",
                                        "borderRadius": "4px",
                                        "hover": {"background": "#f3f4f6", "color": "#ef4444"}
                                    }
                                )
                            ]),
                            html.Div(style={"display": "flex", "gap": "20px"}, children=[
                                html.Div(style={"flex": 1}, children=[
                                    html.Label("Input Field Name", className="form-label"),
                                    dcc.Input(
                                        id={"type": "input-name", "index": "input-field-initial"},
                                        placeholder="Method",
                                        # value="Method",
                                        className="form-input",
                                        style={"height": "38px"}
                                    )
                                ]),
                                html.Div(style={"flex": 1}, children=[
                                    html.Label("Input Field Type", className="form-label"),
                                    dcc.Dropdown(
                                        id={"type": "input-type", "index": "input-field-initial"},
                                        options=[
                                            {"label": "String", "value": "str"},
                                            {"label": "Integer", "value": "int"},
                                            {"label": "Float", "value": "float"},
                                            {"label": "Boolean", "value": "bool"},
                                            {"label": "List", "value": "list"},
                                            {"label": "Literal", "value": "literal"},
                                            {"label": "List Literal", "value": "list_literal"}
                                        ],
                                        value="str",
                                        clearable=False,
                                        style={"height": "38px","border":"1px solid #e1e5e9","border-radius":"6px"}
                                    )
                                ])
                            ]),
                            html.Div([
                                html.Label("Input Field Description", className="form-label"),
                                dcc.Input(
                                    id={"type": "input-description", "index": "input-field-initial"},
                                    placeholder="Describe what this input field represents (e.g., 'The method section of a research paper')",
                                    # value="The method section of a Nature Communications journal article",
                                    className="form-input"
                                )
                            ], className="form-group"),
                            html.Div(style={"display": "flex", "gap": "20px"}, children=[
                                html.Div(style={"flex": 1}, children=[
                                    dcc.Checklist(
                                        id={"type": "input-add-range", "index": "input-field-initial"},
                                        options=[{"label": "Add Range Limits", "value": "true"}],
                                        className="form-checkbox"
                                    )
                                ]),
                                html.Div(style={"flex": 1}, children=[
                                    dcc.Checklist(
                                        id={"type": "input-add-literal", "index": "input-field-initial"},
                                        options=[{"label": "Add Literal List", "value": "true"}],
                                        className="form-checkbox"
                                    )
                                ])
                            ]),
                            html.Div(id={"type": "input-range-container", "index": "input-field-initial"}, style={"display": "none"}, children=[
                                html.Div([
                                    html.Label("Range Minimum", className="form-label"),
                                    dcc.Input(
                                        id={"type": "input-range-min", "index": "input-field-initial"},
                                        type="number",
                                        placeholder="Min value",
                                        className="form-input"
                                    )
                                ], className="form-group"),
                                html.Div([
                                    html.Label("Range Maximum", className="form-label"),
                                    dcc.Input(
                                        id={"type": "input-range-max", "index": "input-field-initial"},
                                        type="number",
                                        placeholder="Max value",
                                        className="form-input"
                                    )
                                ], className="form-group")
                            ]),
                            html.Div(id={"type": "input-literal-container", "index": "input-field-initial"}, style={"display": "none"}, children=[
                                html.Div([
                                    html.Label("Literal List (comma separated)", className="form-label"),
                                    dcc.Input(
                                        id={"type": "input-literal-list", "index": "input-field-initial"},
                                        placeholder="option1,option2,option3",
                                        className="form-input"
                                    )
                                ], className="form-group")
                            ])
                        ], id="input-field-initial", className="section-container", style={"border": "1px solid #e1e5e9", "border-radius": "8px", "padding": "16px", "margin-bottom": "20px"})
                    ])
                ]),
                
                # === OUTPUT FIELDS ===
                html.Div([
                    html.H3("Output Fields", className="section-title"),
                    html.Button(
                        "Add OutputField",
                        id="add-output-field",
                        className="btn",
                        style={"marginBottom": "15px", "height": "32px", "padding": "0 12px", "fontSize": "12px"}
                    ),
                    html.Div(id="output-fields-container", children=[
                        html.Div([
                            html.Div(style={"display": "flex", "justifyContent": "space-between", "alignItems": "flex-start"}, children=[
                                html.H4("Output Field", style={"margin": "0", "fontSize": "16px"}),
                                html.Button(
                                    "×",
                                    id={'type': 'delete-output-field', 'index': 'output-field-initial'},
                                    className="delete-button",
                                    style={
                                        "background": "none",
                                        "border": "none",
                                        "color": "#6b7280",
                                        "fontSize": "20px",
                                        "cursor": "pointer",
                                        "padding": "0 5px",
                                        "lineHeight": "1",
                                        "borderRadius": "4px",
                                        "hover": {"background": "#f3f4f6", "color": "#ef4444"}
                                    }
                                )
                            ]),
                            html.Div(style={"display": "flex", "gap": "20px"}, children=[
                                html.Div(style={"flex": 1}, children=[
                                    html.Label("Output Field Name", className="form-label"),
                                    dcc.Input(
                                        id={"type": "output-name", "index": "output-field-initial"},
                                        placeholder="output_field",
                                        #value="extracted_data",
                                        className="form-input",
                                        style={"height": "38px"}
                                    )
                                ]),
                                html.Div(style={"flex": 1}, children=[
                                    html.Label("Output Field Type", className="form-label"),
                                    dcc.Dropdown(
                                        id={"type": "output-type", "index": "output-field-initial"},
                                        options=[
                                            {"label": "String", "value": "str"},
                                            {"label": "Integer", "value": "int"},
                                            {"label": "Float", "value": "float"},
                                            {"label": "Boolean", "value": "bool"},
                                            {"label": "List", "value": "list"},
                                            {"label": "Literal", "value": "literal"},
                                            {"label": "List Literal", "value": "list_literal"}
                                        ],
                                        value="str",
                                        clearable=False,
                                        style={"height": "38px","border":"1px solid #e1e5e9","border-radius":"6px"}
                                    )
                                ])
                            ]),
                            html.Div([
                                html.Label("Output Field Description", className="form-label"),
                                dcc.Input(
                                    id={"type": "output-description", "index": "output-field-initial"},
                                    placeholder="Description of what to extract",
                                    #value="Extracted data from documents",
                                    className="form-input"
                                )
                            ], className="form-group"),
                            html.Div(style={"display": "flex", "gap": "20px"}, children=[
                                html.Div(style={"flex": 1}, children=[
                                    dcc.Checklist(
                                        id={"type": "output-add-range", "index": "output-field-initial"},
                                        options=[{"label": "Add Range Limits", "value": "true"}],
                                        className="form-checkbox"
                                    )
                                ]),
                                html.Div(style={"flex": 1}, children=[
                                    dcc.Checklist(
                                        id={"type": "output-add-literal", "index": "output-field-initial"},
                                        options=[{"label": "Add Literal List", "value": "true"}],
                                        className="form-checkbox"
                                    )
                                ])
                            ]),
                            html.Div(id={"type": "output-range-container", "index": "output-field-initial"}, style={"display": "none"}, children=[
                                html.Div([
                                    html.Label("Range Minimum", className="form-label"),
                                    dcc.Input(
                                        id={"type": "output-range-min", "index": "output-field-initial"},
                                        type="number",
                                        placeholder="Min value",
                                        className="form-input"
                                    )
                                ], className="form-group"),
                                html.Div([
                                    html.Label("Range Maximum", className="form-label"),
                                    dcc.Input(
                                        id={"type": "output-range-max", "index": "output-field-initial"},
                                        type="number",
                                        placeholder="Max value",
                                        className="form-input"
                                    )
                                ], className="form-group")
                            ]),
                            html.Div(id={"type": "output-literal-container", "index": "output-field-initial"}, style={"display": "none"}, children=[
                                html.Div([
                                    html.Label("Literal List (comma separated)", className="form-label"),
                                    dcc.Input(
                                        id={"type": "output-literal-list", "index": "output-field-initial"},
                                        placeholder="option1,option2,option3",
                                        className="form-input"
                                    )
                                ], className="form-group")
                            ])
                        ], id="output-field-initial", className="section-container", style={"border": "1px solid #e1e5e9", "border-radius": "8px", "padding": "16px", "margin-bottom": "20px"})
                    ])
                ]),
                
                # === PROMPT CONFIGURATION ===
                html.Div([
                    html.H3("Prompt Configuration", className="section-title"),
                    html.Div([
                        html.Label("Initial Prompt", className="form-label"),
                        dcc.Textarea(
                            id="initial-prompt",
                            placeholder="Write your initial prompt template here.\nUse {field_name} placeholders for input fields.",
                            className="form-textarea",
                            style={"height": "120px"}
                        )
                    ], className="form-group")
                ], className="section-container"),
                
                # === OPTIMIZATION SETTINGS ===
                html.Div([
                    html.H3("Optimization Settings", className="section-title"),
                    html.Div([
                        html.Label("Task", className="form-label"),
                        dcc.Dropdown(
                            id="task",
                            options=[
                                {"label": "QA", "value": "QA"},
                                {"label": "Extraction", "value": "Extraction"}
                            ],
                            value="Extraction",
                            clearable=False,
                            style={"height": "38px","border":"1px solid #e1e5e9","border-radius":"6px"}
                        )
                    ], className="form-group"),
                    html.Div([
                        html.Label("Optimization Burden", className="form-label"),
                        dcc.Dropdown(
                            id="optim-burden",
                            options=[
                                {"label": "Light", "value": "light"},
                                {"label": "Medium", "value": "medium"},
                                {"label": "Heavy", "value": "heavy"}
                            ],
                            value="medium",
                            clearable=False,
                            style={"height": "38px","border":"1px solid #e1e5e9","border-radius":"6px"}
                        )
                    ], className="form-group"),
                    html.Div([
                        html.Label("Threads", className="form-label"),
                        dcc.Input(
                            id="threads",
                            type="number",
                            placeholder="6",
                            value=6,
                            className="form-input"
                        )
                    ], className="form-group"),
                    html.Div([
                        html.Label("Demos", className="form-label"),
                        dcc.Input(
                            id="demos",
                            type="number",
                            placeholder="1",
                            value=1,
                            className="form-input"
                        )
                    ], className="form-group")
                ], className="section-container"),
                
                # === EXTRACTION MODE ===
                html.Div([
                    html.H3("Extraction Mode", className="section-title"),
                    html.Div([
                        html.Label("Multiple Entities", className="form-label"),
                        dcc.Checklist(
                            id="multiple",
                            options=[{"label": "Set true for extracting multiple entities from the document", "value": "true"}],
                            value=[],
                            className="form-checkbox"
                        )
                    ], className="form-group"),
                    html.Div([
                        html.Label("AI Evaluation", className="form-label"),
                        dcc.Checklist(
                            id="ai-evaluation",
                            options=[{"label": "Set true to use AI scoring instead of string matching", "value": "true"}],
                            value=["true"],
                            className="form-checkbox"
                        )
                    ], className="form-group")
                ], className="section-container"),
                
                # === ACTION BUTTONS ===
                html.Div([
                    html.Button(
                        "Run Optimization",
                        id="run-optimization",
                        className="btn btn-primary",
                        style={"marginRight": "10px", "height": "38px", "padding": "0 20px"}
                    )
                ], className="form-actions"),
                
                # === OPTIMIZATION RESULTS ===
                html.Div(id="optimization-results", className="results-container"),
                
                # === CONFIGURATION LOAD STATUS ===
                html.Div(id="optim-config-load-status", style={"display": "none"}),
                
                # === CONFIGURATION MODAL ===
                html.Div([
                    dbc.Modal([
                        dbc.ModalHeader("Configuration Loaded"),
                        dbc.ModalBody(id="optim-config-modal-body"),
                        dbc.ModalFooter([
                            dbc.Button("Close", id="close-optim-config-modal", className="ml-auto")
                        ])
                    ], id="optim-config-modal", is_open=False)
                ])
                
            ])
        ], className="module-container"),
        
        # === RECENT PROMPT OPTIMIZATION TASKS ===
        html.Div([
            html.H3("Recent Prompt Optimization Tasks", className="section-title"),
            html.Div([
                html.P("The following are the most recent prompt optimization tasks, showing task name, creation time, and status information.", 
                      className="help-text-description", style={"marginBottom": "15px"})
            ]),
            create_task_card_list(generate_task_data_from_runs("runs/prompt_optimization", 10, "prompt-optimization"))
        ], className="module-container", style={"marginTop": "30px"})
    ])

